### ISSUE TITLE
Differentiate videos from photos

### ISSUE THREAD

**Issue by victornoel** [danfunk/ethans_fight#1]
Hi,

It would be nice if the difference is made between a post of type picture and a post of type video.

They both have an object_id, but the current code seems to not work when there is a video...

**Comment by danfunk** [comment]
Hey Victor, thanks for the comment.  I noticed videos wern't working, but I hadn't dug into it yet.  Good point.

**Comment by danfunk** [comment]
I have videos downloading correctly from you-tube, but I'm struggling with the ones directly posted to facebook, I'm thinking I'll need a key generated from the account that uploaded these videos.  Odd that I can get part of a video before it bombs out.

**Comment by victornoel** [comment]
Hi,

That's strange yes, did you try downloading it by hand using wget? I tried with a public video and it works... but I noticed a lot of problems with accessing photos and videos using Graph API, I don't know if I'm missing something with permissions, but for some videos I want to access I get the "Unsupported get request." error message, while for other it works as desired... (both videos being public). I think there is a lot of undocumented behaviour of Graph API...

Also, maybe it would be best to have a switch for downloading videos or not, maybe also differenciating facebook videos from other websites.
For example I would like to download only fb videos (when we can make it work) and only have the link (or embedded video) for youtube and other websites.
Or I could want to only have the link (or embedded) for everything.

**Comment by victornoel** [comment]
I saw your last commit, I'm currently testing it :)

I found a first (very small) bug: the content/videos folder is not created beforehand so the rename fails but creating the folder fixes the problem of course.

**Comment by danfunk** [comment]
Victor you are delightful. I've added you as a contributor.  Please fee
free to commit to the repo.

**Comment by victornoel** [comment]
Cool, that seems to work :)
