### ISSUE TITLE
Include pictures in comments

### ISSUE THREAD

**Issue by victornoel** [danfunk/ethans_fight#2]
Hi,

Pictures in comments are currently not downloaded.
I guess it should be the same if there is a video...

**Comment by danfunk** [comment]
There are great Victor.  Thank you.

**Comment by victornoel** [comment]
Hi, I looked a bit at this one, and when using the graph explorer from Facebook it looks like there is no field attached to the comments giving a hint that there is an attached picture...

https://developers.facebook.com/docs/reference/api/Comment/ refers to the attribute attachment but I didn't see it for the examples I looked at... But it is the first time I check the Graph API, not sure how it works :)

Anyway, great app!

**Comment by danfunk** [comment]
put this comment on the wrong ticket.
