### ISSUE TITLE
Links in post are skipped

### ISSUE THREAD

**Issue by victornoel** [danfunk/ethans_fight#3]
When a post has a link (in the "link" attribute), the current code does not take it into account.

For example if one share a youtube video, only the text will appear but not the link.

**Comment by danfunk** [comment]
Hurm.  I thought external links were displayed correctly for posts.  Not sure this would happen for comments.  I'll take another look.

**Comment by victornoel** [comment]
I think it is because in the post template, there is the following test:

```
#if (@post.type == "link") :
   <a href="@{post.link}">Original Post</a>
#end
```

And if the post is about a video on youtube for example, the type is video, not link. I guess the best would be to test for the existence of the link field and just add it if it is there.

**Comment by danfunk** [comment]
This is corrected and should show up if there is a link available.

**Comment by victornoel** [comment]
Now things are half better, half worst ;)
In particular some pictures are tried to be downloaded but result in empty file (well, they are not empty they are strange, all are 43kb...), I think it is the result of trying to download a picture link of the form:
"https://fbexternal-a.akamaihd.net/safe_image.php?d=AQCPlOMrtSTHdn9w&w=130&h=130&url=http%3A%2F%2Fi1.ytimg.com%2Fvi%2F-wsS0uJ7Vww%2Fhqdefault.jpg%3Ffeature%3Dog"

Which is just a thumbnail for a youtube link.

I would propose the following:

For video post (type == "video")
Include "post.link" as "View Link" (or View Video), or better, embed the video using the post.source field (both is the best :).
The picture link is interesting for having a small thumbnail, but it doesn't get downloaded properly, maybe because of the type of link... 
Here is an example of video post: /5396343309_10151769788918310/
But if it has an "object_id", then it means it is a facebook video, so things are a bit different, for example the source and link seems to contain the video itself, so maybe we could download it (which would make sense in my opinion, if we want to backup a group) and potentially embed it, for example as a starter using the html5 video markup element (http://www.w3schools.com/html/html5_video.asp)
See for example: /5396343309_10151748949568310/

For photo post (type == "photo")
Include "picture" for small and get the large image as already done with "object_id" and its source attribute.
I noticed some photo object have multiple but they do not seem to be ordered, they are just old version of the same object, so let's not bother about them for now.

For link post (type == "link")
"picture" is an image extracted from the page linked, not so important, but it could be nice to have it, except that it is the same type of link than those for youtube video that doesn't get downloaded...
"link" is the link, and your code seems correct about it :)
An example: /5396343309_10151753952953310/

So, there is no real change for photo post, but there is for video post, and for links in these.
Mainly, I would always print the "link" field, even if it is not a type == "link", except for posts with an object_id because the link will target a facebook element.
If there is an object_id I would make the difference between video and photo and download it properly (because for now video are not).

I don't know if a post with a link to a picture is considered type link or type photo...

Well, that's a lot of things, I hope it's helpful :)

**Comment by danfunk** [comment]
Very Helpful.  Thank you Victor.  I'm trying to make this work for a friend
of mine, and I'm finding that the Graph API will only allow you to download
vidoes you own, or are tagged in.  Otherwise I'm getting an error.  For me
to keep testing on this group I've got.  Getting a downloaded archived
version of the movies is critical to my project as well.  Thanks for the
detailed feedback.
