### ISSUE TITLE
Support pagination for comments

### ISSUE THREAD

**Issue by victornoel** [danfunk/ethans_fight#4]
Hi,

Comments in post have pagination, currently the app does not extract all of them, only the first page.

**Comment by danfunk** [comment]
I thought about that, then forgot.  These are all excellent tickets, thanks for the feedback.  I look forward to digging in and getting this corrected.

**Comment by victornoel** [comment]
Ok, I have a group with lot of comments, pictures, videos, and so on that I'd like to archive properly, it makes a great source for beta testing, especially because I read everything there, so I can easily spot the missing things.
I will try to give you good bug reports, and if I'm able, look for fixes :)

**Comment by danfunk** [comment]
That would rock Victor.

**Comment by danfunk** [comment]
This is fixed.

**Comment by victornoel** [comment]
I'm not totally sure it's working as expected... For a reason I don't understand, graph API does not returns what it should when the next page for comments is requested... it returns the first page of comments (I tried in the Graph API explorer). So I don't know...

I tried to find an example:
if you ask for this group with Graph API: /194856060675255/feed
(it is https://www.facebook.com/groups/IMA.Literary.Tradition/)
and look at the post with ID 194856060675255_215139301980264
(it is https://www.facebook.com/groups/IMA.Literary.Tradition/permalink/215139301980264/)
you will see it has a "next" page for the comments, but if you call this next page, you don't get all the remaining comments as wanted.

The only solution I found for that is using this kind of request which returns the comments without limit:
/194856060675255/feed?fields=id,message,comments.limit(500)

But then you need to add by hand every field you want from the posts...

Also, I think you forgot to uncomment the recursive call for more pages and some test prints :)

**Comment by danfunk** [comment]
Victor you are a saint of patience.  Excellent feedback, and a great
recommendation.  I'll give it a shot.

**Comment by victornoel** [comment]
And then I think we could use the same thing to process comments in create_photo_page, if I'm not mistaken about how things are structured :)
(and you left again a print of all the comments)
